data:
  img_dir: "data/Flicker8k_Dataset"
  captions_file: "data/Flickr8k.token.txt"
  train_file: "data/Flickr_8k.trainImages.txt"
  test_file: "data/Flickr_8k.testImages.txt"

model:
  embed_size: 256
  hidden_size: 512
  num_layers: 1
  dropout: 0.5

training:
  batch_size: 32
  num_epochs: 35
  learning_rate: 0.001
  freq_threshold: 5

output:
  model_dir: "outputs/"