data:
  img_dir: "/kaggle/input/datasets/adityajn105/flickr30k/Images"
  captions_file: "/kaggle/input/datasets/adityajn105/flickr30k/captions.txt"
  train_file: null
  test_file: null

model:
  embed_size: 256
  hidden_size: 512
  num_layers: 1
  dropout: 0.5

training:
  batch_size: 32
  num_epochs: 35
  learning_rate: 0.001
  freq_threshold: 5

output:
  model_dir: "outputs/"